extend type Task {
  """
  ✨ Implicit foreign key field based on `Task`.`assignedTo`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  assignedToId: UUID @fdc_generated(from: "Task.assignedTo", purpose: IMPLICIT_REF_FIELD)
}
extend type TaskComment {
  """
  ✨ Implicit foreign key field based on `TaskComment`.`task`. It must match the value of `Task`.`id`. See `@ref` for how to customize it.
  """
  taskId: UUID! @fdc_generated(from: "TaskComment.task", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `TaskComment`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "TaskComment.user", purpose: IMPLICIT_REF_FIELD)
}
