extend type Query {
  """
  ✨ Look up a single `AIQuery` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  aIQuery(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: AIQuery_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AIQuery_FirstRow
  ): AIQuery @fdc_generated(from: "AIQuery", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `ActivityLog` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  activityLog(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ActivityLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ActivityLog_FirstRow
  ): ActivityLog @fdc_generated(from: "ActivityLog", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Business` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  business(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Business_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Business_FirstRow
  ): Business @fdc_generated(from: "Business", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Customer` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  customer(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Customer_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Customer_FirstRow
  ): Customer @fdc_generated(from: "Customer", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Document` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  document(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Document_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Document_FirstRow
  ): Document @fdc_generated(from: "Document", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Employee` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  employee(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Employee_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Employee_FirstRow
  ): Employee @fdc_generated(from: "Employee", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Notification` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  notification(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Notification_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Notification_FirstRow
  ): Notification @fdc_generated(from: "Notification", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Product` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  product(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Product_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Product_FirstRow
  ): Product @fdc_generated(from: "Product", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Supplier` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  supplier(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Supplier_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Supplier_FirstRow
  ): Supplier @fdc_generated(from: "Supplier", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Task` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  task(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Task_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Task_FirstRow
  ): Task @fdc_generated(from: "Task", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `TaskComment` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  taskComment(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: TaskComment_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TaskComment_FirstRow
  ): TaskComment @fdc_generated(from: "TaskComment", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Tenant` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  tenant(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Tenant_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Tenant_FirstRow
  ): Tenant @fdc_generated(from: "Tenant", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Transaction` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  transaction(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Transaction_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Transaction_FirstRow
  ): Transaction @fdc_generated(from: "Transaction", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ List `AIQuery` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  aIQueries(
    """
    Filter condition to narrow down the query results.
    """
    where: AIQuery_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [AIQuery_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: AIQuery_Having
  ): [AIQuery!]! @fdc_generated(from: "AIQuery", purpose: QUERY_MULTIPLE)
  """
  ✨ List `ActivityLog` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  activityLogs(
    """
    Filter condition to narrow down the query results.
    """
    where: ActivityLog_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ActivityLog_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ActivityLog_Having
  ): [ActivityLog!]! @fdc_generated(from: "ActivityLog", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Business` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  businesses(
    """
    Filter condition to narrow down the query results.
    """
    where: Business_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Business_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Business_Having
  ): [Business!]! @fdc_generated(from: "Business", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Customer` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  customers(
    """
    Filter condition to narrow down the query results.
    """
    where: Customer_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Customer_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Customer_Having
  ): [Customer!]! @fdc_generated(from: "Customer", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Document` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  documents(
    """
    Filter condition to narrow down the query results.
    """
    where: Document_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Document_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Document_Having
  ): [Document!]! @fdc_generated(from: "Document", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Employee` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  employees(
    """
    Filter condition to narrow down the query results.
    """
    where: Employee_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Employee_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Employee_Having
  ): [Employee!]! @fdc_generated(from: "Employee", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Notification` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  notifications(
    """
    Filter condition to narrow down the query results.
    """
    where: Notification_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Notification_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Notification_Having
  ): [Notification!]! @fdc_generated(from: "Notification", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Product` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  products(
    """
    Filter condition to narrow down the query results.
    """
    where: Product_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Product_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Product_Having
  ): [Product!]! @fdc_generated(from: "Product", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Supplier` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  suppliers(
    """
    Filter condition to narrow down the query results.
    """
    where: Supplier_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Supplier_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Supplier_Having
  ): [Supplier!]! @fdc_generated(from: "Supplier", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Task` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  tasks(
    """
    Filter condition to narrow down the query results.
    """
    where: Task_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Task_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Task_Having
  ): [Task!]! @fdc_generated(from: "Task", purpose: QUERY_MULTIPLE)
  """
  ✨ List `TaskComment` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  taskComments(
    """
    Filter condition to narrow down the query results.
    """
    where: TaskComment_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [TaskComment_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: TaskComment_Having
  ): [TaskComment!]! @fdc_generated(from: "TaskComment", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Tenant` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  tenants(
    """
    Filter condition to narrow down the query results.
    """
    where: Tenant_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Tenant_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Tenant_Having
  ): [Tenant!]! @fdc_generated(from: "Tenant", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Transaction` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  transactions(
    """
    Filter condition to narrow down the query results.
    """
    where: Transaction_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Transaction_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Transaction_Having
  ): [Transaction!]! @fdc_generated(from: "Transaction", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
}
