extend type AIQuery {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "AIQuery", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `AIQuery` table.
  """
  _count: Int! @fdc_generated(from: "AIQuery.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AIQuery` table where the `businessId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  businessId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AIQuery.businessId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AIQuery` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AIQuery.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AIQuery` table where the `queryText` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  queryText_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AIQuery.queryText", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AIQuery` table where the `response` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  response_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AIQuery.response", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AIQuery` table where the `tenantId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  tenantId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AIQuery.tenantId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AIQuery` table where the `timestamp` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  timestamp_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AIQuery.timestamp", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AIQuery` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AIQuery.userId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `timestamp` field in the `AIQuery` table.
  """
  timestamp_min: Timestamp @fdc_generated(from: "AIQuery.timestamp", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `timestamp` field in the `AIQuery` table.
  """
  timestamp_max: Timestamp @fdc_generated(from: "AIQuery.timestamp", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "AIQuery.id", purpose: ENTITY_ID)
}
extend type ActivityLog {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "ActivityLog", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `ActivityLog` table.
  """
  _count: Int! @fdc_generated(from: "ActivityLog.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ActivityLog` table where the `actionType` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  actionType_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ActivityLog.actionType", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ActivityLog` table where the `businessId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  businessId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ActivityLog.businessId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ActivityLog` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ActivityLog.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ActivityLog` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ActivityLog.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ActivityLog` table where the `module` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  module_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ActivityLog.module", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ActivityLog` table where the `recordId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  recordId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ActivityLog.recordId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ActivityLog` table where the `tenantId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  tenantId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ActivityLog.tenantId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ActivityLog` table where the `timestamp` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  timestamp_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ActivityLog.timestamp", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ActivityLog` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ActivityLog.userId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ActivityLog` table where the `userName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ActivityLog.userName", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `timestamp` field in the `ActivityLog` table.
  """
  timestamp_min: Timestamp @fdc_generated(from: "ActivityLog.timestamp", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `timestamp` field in the `ActivityLog` table.
  """
  timestamp_max: Timestamp @fdc_generated(from: "ActivityLog.timestamp", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "ActivityLog.id", purpose: ENTITY_ID)
}
extend type Business {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Business", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Business` table.
  """
  _count: Int! @fdc_generated(from: "Business.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Business` table where the `businessType` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  businessType_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Business.businessType", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Business` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Business.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Business` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Business.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Business` table where the `location` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  location_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Business.location", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Business` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Business.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Business` table where the `region` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  region_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Business.region", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Business` table where the `tenantId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  tenantId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Business.tenantId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `Business` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Business.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Business` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Business.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Business.id", purpose: ENTITY_ID)
}
extend type Customer {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Customer", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Customer` table.
  """
  _count: Int! @fdc_generated(from: "Customer.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Customer` table where the `businessId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  businessId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Customer.businessId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Customer` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Customer.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Customer` table where the `customerName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  customerName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Customer.customerName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Customer` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Customer.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Customer` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Customer.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Customer` table where the `phoneNumber` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  phoneNumber_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Customer.phoneNumber", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Customer` table where the `tenantId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  tenantId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Customer.tenantId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `Customer` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Customer.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Customer` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Customer.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Customer.id", purpose: ENTITY_ID)
}
extend type Document {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Document", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Document` table.
  """
  _count: Int! @fdc_generated(from: "Document.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Document` table where the `businessId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  businessId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Document.businessId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Document` table where the `documentType` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  documentType_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Document.documentType", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Document` table where the `fileUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  fileUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Document.fileUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Document` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Document.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Document` table where the `tenantId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  tenantId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Document.tenantId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Document` table where the `title` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  title_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Document.title", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Document` table where the `uploadedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  uploadedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Document.uploadedAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Document` table where the `uploadedBy` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  uploadedBy_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Document.uploadedBy", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `uploadedAt` field in the `Document` table.
  """
  uploadedAt_min: Timestamp @fdc_generated(from: "Document.uploadedAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `uploadedAt` field in the `Document` table.
  """
  uploadedAt_max: Timestamp @fdc_generated(from: "Document.uploadedAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Document.id", purpose: ENTITY_ID)
}
extend type Employee {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Employee", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Employee` table.
  """
  _count: Int! @fdc_generated(from: "Employee.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Employee` table where the `businessId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  businessId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Employee.businessId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Employee` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Employee.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Employee` table where the `department` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  department_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Employee.department", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Employee` table where the `fullName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  fullName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Employee.fullName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Employee` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Employee.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Employee` table where the `position` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  position_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Employee.position", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Employee` table where the `salary` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  salary_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Employee.salary", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Employee` table where the `startDate` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  startDate_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Employee.startDate", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Employee` table where the `status` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  status_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Employee.status", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Employee` table where the `tenantId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  tenantId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Employee.tenantId", purpose: QUERY_COUNT)
  """
  ✨ Sum the `salary` field in the `Employee` table.
  """
  salary_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Employee.salary", purpose: QUERY_SUM)
  """
  ✨ Average the `salary` field in the `Employee` table.
  """
  salary_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Employee.salary", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `createdAt` field in the `Employee` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Employee.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `salary` field in the `Employee` table.
  """
  salary_min: Float @fdc_generated(from: "Employee.salary", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `startDate` field in the `Employee` table.
  """
  startDate_min: Date @fdc_generated(from: "Employee.startDate", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Employee` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Employee.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `salary` field in the `Employee` table.
  """
  salary_max: Float @fdc_generated(from: "Employee.salary", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `startDate` field in the `Employee` table.
  """
  startDate_max: Date @fdc_generated(from: "Employee.startDate", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Employee.id", purpose: ENTITY_ID)
}
extend type Notification {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Notification", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Notification` table.
  """
  _count: Int! @fdc_generated(from: "Notification.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Notification` table where the `businessId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  businessId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Notification.businessId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Notification` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Notification.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Notification` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Notification.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Notification` table where the `isRead` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  isRead_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Notification.isRead", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Notification` table where the `message` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  message_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Notification.message", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Notification` table where the `tenantId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  tenantId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Notification.tenantId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Notification` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Notification.userId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `Notification` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Notification.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Notification` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Notification.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Notification.id", purpose: ENTITY_ID)
}
extend type Product {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Product", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Product` table.
  """
  _count: Int! @fdc_generated(from: "Product.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `businessId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  businessId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.businessId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `category` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  category_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.category", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `costPrice` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  costPrice_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.costPrice", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `createdBy` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdBy_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.createdBy", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `expiryDate` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  expiryDate_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.expiryDate", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `lowStockLevel` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  lowStockLevel_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.lowStockLevel", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `quantity` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  quantity_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.quantity", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `sellingPrice` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  sellingPrice_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.sellingPrice", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `tenantId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  tenantId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.tenantId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Product` table where the `updatedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  updatedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Product.updatedAt", purpose: QUERY_COUNT)
  """
  ✨ Sum the `costPrice` field in the `Product` table.
  """
  costPrice_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Product.costPrice", purpose: QUERY_SUM)
  """
  ✨ Sum the `lowStockLevel` field in the `Product` table.
  """
  lowStockLevel_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Product.lowStockLevel", purpose: QUERY_SUM)
  """
  ✨ Sum the `quantity` field in the `Product` table.
  """
  quantity_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Product.quantity", purpose: QUERY_SUM)
  """
  ✨ Sum the `sellingPrice` field in the `Product` table.
  """
  sellingPrice_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Product.sellingPrice", purpose: QUERY_SUM)
  """
  ✨ Average the `costPrice` field in the `Product` table.
  """
  costPrice_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Product.costPrice", purpose: QUERY_AVG)
  """
  ✨ Average the `lowStockLevel` field in the `Product` table.
  """
  lowStockLevel_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Product.lowStockLevel", purpose: QUERY_AVG)
  """
  ✨ Average the `quantity` field in the `Product` table.
  """
  quantity_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Product.quantity", purpose: QUERY_AVG)
  """
  ✨ Average the `sellingPrice` field in the `Product` table.
  """
  sellingPrice_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Product.sellingPrice", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `costPrice` field in the `Product` table.
  """
  costPrice_min: Float @fdc_generated(from: "Product.costPrice", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `createdAt` field in the `Product` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Product.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `expiryDate` field in the `Product` table.
  """
  expiryDate_min: Date @fdc_generated(from: "Product.expiryDate", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `lowStockLevel` field in the `Product` table.
  """
  lowStockLevel_min: Int @fdc_generated(from: "Product.lowStockLevel", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `quantity` field in the `Product` table.
  """
  quantity_min: Int @fdc_generated(from: "Product.quantity", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `sellingPrice` field in the `Product` table.
  """
  sellingPrice_min: Float @fdc_generated(from: "Product.sellingPrice", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `updatedAt` field in the `Product` table.
  """
  updatedAt_min: Timestamp @fdc_generated(from: "Product.updatedAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `costPrice` field in the `Product` table.
  """
  costPrice_max: Float @fdc_generated(from: "Product.costPrice", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `createdAt` field in the `Product` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Product.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `expiryDate` field in the `Product` table.
  """
  expiryDate_max: Date @fdc_generated(from: "Product.expiryDate", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `lowStockLevel` field in the `Product` table.
  """
  lowStockLevel_max: Int @fdc_generated(from: "Product.lowStockLevel", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `quantity` field in the `Product` table.
  """
  quantity_max: Int @fdc_generated(from: "Product.quantity", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `sellingPrice` field in the `Product` table.
  """
  sellingPrice_max: Float @fdc_generated(from: "Product.sellingPrice", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `updatedAt` field in the `Product` table.
  """
  updatedAt_max: Timestamp @fdc_generated(from: "Product.updatedAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Product.id", purpose: ENTITY_ID)
}
extend type Supplier {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Supplier", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Supplier` table.
  """
  _count: Int! @fdc_generated(from: "Supplier.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Supplier` table where the `businessId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  businessId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Supplier.businessId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Supplier` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Supplier.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Supplier` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Supplier.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Supplier` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Supplier.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Supplier` table where the `phoneNumber` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  phoneNumber_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Supplier.phoneNumber", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Supplier` table where the `supplierName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  supplierName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Supplier.supplierName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Supplier` table where the `tenantId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  tenantId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Supplier.tenantId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `Supplier` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Supplier.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Supplier` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Supplier.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Supplier.id", purpose: ENTITY_ID)
}
extend type Task {
  """
  ✨ List `TaskComment` objects in a one-to-many relationship (where `TaskComment`.`task` is this object).
  """
  taskComments_on_task(
    """
    Filter condition to narrow down the query results.
    """
    where: TaskComment_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [TaskComment_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: TaskComment_Having
  ): [TaskComment!]! @fdc_generated(from: "TaskComment.task", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Task", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Task` table.
  """
  _count: Int! @fdc_generated(from: "Task.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Task` table where the `assignedToId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  assignedToId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Task.assignedToId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Task` table where the `businessId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  businessId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Task.businessId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Task` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Task.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Task` table where the `createdBy` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdBy_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Task.createdBy", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Task` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Task.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Task` table where the `dueDate` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  dueDate_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Task.dueDate", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Task` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Task.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Task` table where the `priority` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  priority_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Task.priority", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Task` table where the `status` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  status_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Task.status", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Task` table where the `tenantId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  tenantId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Task.tenantId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Task` table where the `title` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  title_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Task.title", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Task` table where the `updatedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  updatedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Task.updatedAt", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `Task` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Task.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `dueDate` field in the `Task` table.
  """
  dueDate_min: Timestamp @fdc_generated(from: "Task.dueDate", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `updatedAt` field in the `Task` table.
  """
  updatedAt_min: Timestamp @fdc_generated(from: "Task.updatedAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Task` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Task.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `dueDate` field in the `Task` table.
  """
  dueDate_max: Timestamp @fdc_generated(from: "Task.dueDate", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `updatedAt` field in the `Task` table.
  """
  updatedAt_max: Timestamp @fdc_generated(from: "Task.updatedAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Task.id", purpose: ENTITY_ID)
}
extend type TaskComment {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "TaskComment", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `TaskComment` table.
  """
  _count: Int! @fdc_generated(from: "TaskComment.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TaskComment` table where the `businessId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  businessId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TaskComment.businessId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TaskComment` table where the `content` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  content_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TaskComment.content", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TaskComment` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TaskComment.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TaskComment` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TaskComment.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TaskComment` table where the `taskId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  taskId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TaskComment.taskId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TaskComment` table where the `tenantId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  tenantId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TaskComment.tenantId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TaskComment` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TaskComment.userId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `TaskComment` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "TaskComment.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `TaskComment` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "TaskComment.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "TaskComment.id", purpose: ENTITY_ID)
}
extend type Tenant {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Tenant", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Tenant` table.
  """
  _count: Int! @fdc_generated(from: "Tenant.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Tenant` table where the `businessSector` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  businessSector_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Tenant.businessSector", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Tenant` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Tenant.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Tenant` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Tenant.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Tenant` table where the `location` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  location_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Tenant.location", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Tenant` table where the `logoUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  logoUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Tenant.logoUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Tenant` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Tenant.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Tenant` table where the `ownerEmail` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  ownerEmail_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Tenant.ownerEmail", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Tenant` table where the `subscriptionTier` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  subscriptionTier_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Tenant.subscriptionTier", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Tenant` table where the `taxId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  taxId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Tenant.taxId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `Tenant` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Tenant.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Tenant` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Tenant.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Tenant.id", purpose: ENTITY_ID)
}
extend type Transaction {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Transaction", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Transaction` table.
  """
  _count: Int! @fdc_generated(from: "Transaction.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Transaction` table where the `amount` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  amount_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Transaction.amount", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Transaction` table where the `businessId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  businessId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Transaction.businessId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Transaction` table where the `category` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  category_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Transaction.category", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Transaction` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Transaction.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Transaction` table where the `date` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  date_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Transaction.date", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Transaction` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Transaction.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Transaction` table where the `receiptUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  receiptUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Transaction.receiptUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Transaction` table where the `recordedBy` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  recordedBy_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Transaction.recordedBy", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Transaction` table where the `tenantId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  tenantId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Transaction.tenantId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Transaction` table where the `type` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  type_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Transaction.type", purpose: QUERY_COUNT)
  """
  ✨ Sum the `amount` field in the `Transaction` table.
  """
  amount_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Transaction.amount", purpose: QUERY_SUM)
  """
  ✨ Average the `amount` field in the `Transaction` table.
  """
  amount_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Transaction.amount", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `amount` field in the `Transaction` table.
  """
  amount_min: Float @fdc_generated(from: "Transaction.amount", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `createdAt` field in the `Transaction` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Transaction.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `date` field in the `Transaction` table.
  """
  date_min: Timestamp @fdc_generated(from: "Transaction.date", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `amount` field in the `Transaction` table.
  """
  amount_max: Float @fdc_generated(from: "Transaction.amount", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `createdAt` field in the `Transaction` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Transaction.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `date` field in the `Transaction` table.
  """
  date_max: Timestamp @fdc_generated(from: "Transaction.date", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Transaction.id", purpose: ENTITY_ID)
}
extend type User {
  """
  ✨ List `Task` objects in a one-to-many relationship (where `Task`.`assignedTo` is this object).
  """
  tasks_on_assignedTo(
    """
    Filter condition to narrow down the query results.
    """
    where: Task_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Task_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Task_Having
  ): [Task!]! @fdc_generated(from: "Task.assignedTo", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `TaskComment` objects in a one-to-many relationship (where `TaskComment`.`user` is this object).
  """
  taskComments_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: TaskComment_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [TaskComment_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: TaskComment_Having
  ): [TaskComment!]! @fdc_generated(from: "TaskComment.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "User", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `User` table.
  """
  _count: Int! @fdc_generated(from: "User.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `businessId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  businessId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.businessId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `department` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  department_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.department", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `phoneNumber` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  phoneNumber_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.phoneNumber", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `role` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  role_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.role", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `tenantId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  tenantId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.tenantId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `User` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "User.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `User` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "User.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "User.id", purpose: ENTITY_ID)
}
